### ISSUE TITLE
Possible KiCad 6.0 problem?

### ISSUE THREAD

**Issue by haplm** [mkvenkit/mico#2]
First, let me say that this is an awesome project, thank you!

I have tried to load it into KiCad, and it seems that some pads (mostly GND, see eg. the USB connector) are not connected. Is this is problem with 5.x to 6.0 conversion, or is it intentional?

<img width="1278" alt="Screenshot 2021-12-28 at 7 11 26" src="https://user-images.githubusercontent.com/295448/147534464-ff0cd172-5945-4174-8e95-bd7dde7d22f3.png">

**Comment by mkvenkit** [comment]
Thanks! It’s probably an oversight. Adding @sivaprakazh for comment.

**Comment by sivaprakazh** [comment]
@haplm After loading the file press the B button in your computer, It will fill the copper.

**Comment by haplm** [comment]
Right, thank you, it works. I need to get better at KiCad...
