### ISSUE TITLE
Available for purchase?

### ISSUE THREAD

**Issue by Tormund1985** [mkvenkit/mico#3]
I am interested in this product. It could be possible purchase a few ones to test it?

Thanks.

**Comment by mahesh-electronut** [comment]
Thanks for you interest! We're not manufacturing Mico yet. Please follow me on [Twitter [](](https://twitter.com/mkvenkit)for) updates.

**Comment by mkvenkit** [comment]
Thanks for you interest! We're not manufacturing Mico yet. Please follow me on [Twitter ](https://twitter.com/mkvenkit) for updates.

**Comment by jlpoolen** [comment]
I'm looking into getting a quotation from an assembly firm to produce a turn-key product.  It would be helpful for me if I had an idea of interest and wonder if I might post a survey here to measure interested/potential subscribers to a crowd-funded effort to product this product.

I would need to verify that this would be ready for production, like have some sample audio files used for testing and having the test results made available.  Is this something you would be interested in supporting?

**Comment by mahesh-electronut** [comment]
> I'm looking into getting a quotation from an assembly firm to produce a turn-key product. It would be helpful for me if I had an idea of interest and wonder if I might post a survey here to measure interested/potential subscribers to a crowd-funded effort to product this product.
> 
> I would need to verify that this would be ready for production, like have some sample audio files used for testing and having the test results made available. Is this something you would be interested in supporting?

Please see my reply to #4

**Comment by Tormund1985** [comment]
> I'm looking into getting a quotation from an assembly firm to produce a turn-key product. It would be helpful for me if I had an idea of interest and wonder if I might post a survey here to measure interested/potential subscribers to a crowd-funded effort to product this product.
> 
> I would need to verify that this would be ready for production, like have some sample audio files used for testing and having the test results made available. Is this something you would be interested in supporting?

I am sorry for the delay, i would be interested first in only one to test in my project. Exponentially if it works maybe around 25 units. My intention is to connect it to a raspberry pi zero 2 as a spy-mic.

**Comment by mahesh-electronut** [comment]
@Tormund1985 I am working with Crowd Supply to crowdfund production. Please follow me on Twitter for updates on the campaign.
