### ISSUE TITLE
Kickstarter To Manufacture "Mico" Underway

### ISSUE THREAD

**Issue by jlpoolen** [mkvenkit/mico#4]
I've decided to move forward and explore having a Kickstarter program to do a production run of this component.  I'm awaiting a "turn-key" quotation from  PCBAssemblyExpress in Oregon,  When I have the quotation and hear back from Mahesh, I'll update this issue.  See Issue #3 

I have no experience with Kickstarter, but believe it to be a highly reputable company.  Mahesh seems to have done all the leg work and produced a ready-to-manufacture product.  So the question now is whether there would be demand to generate a production run.  And, of course, at what cost.  I am thinking if I can obtain a quotation for ready-to-use components, the only other task would be fulfillment and I am looking at https://www.easyship.com to handle that so that my role in this matter is simply managerial.

**Comment by mkvenkit** [comment]
Hi John,

I am already working on manufacturing Mico. I open-sourced Mico so people could learn from the design and build it for personal use. But if you plan to manufacture it for commercial use, you'll need to license the design from me. I've updated the readme to make this clear.

Thanks

**Comment by jlpoolen** [comment]
Hi Mahesh,

I have no desire to commercialize the product.  I simply would like to have a working unit and thought a Kickstarter project would accomplish that passing the cost onto subscribers.  If you want a license fee, that could be worked in, I have no problem with that.  But you have _now_ indicated you are working on manufacturing so I see no point in pursuing the matter from my standpoint.  Unless you'd like to collaborate, I'll stop pursuing this and await your announcement of a plan and estimated shipping date.

Cheers,
John

**Comment by mahesh-electronut** [comment]
Hi John,

I appreciate your response. If you need a working unit, I can send you one. Please email me at info@electronut.in . So many people are interested in this product, but it takes time to plan out manufacturing. I might make a small batch myself so I can send out samples. Thanks for your interest.

**Comment by jlpoolen** [comment]
Hi Mahesh,

No need to send me one, I'll await what your manufacturing pursuit reveals.  In the meantime, I copied you with a private email to the company I was approaching.  Your project segues into another larger project I have in mind, but I'm still a far distance away from that other project and thought having the microphone component settled and proven would be a minor milestone.  I should note that I had as a desirable goal that the product be manufactured here in the United States (I thought this might be a good selling point)... yes, at greater cost.  I grow weary of products breaking down and would like to deal with a company that has accountability. 

This project is your baby... so run with it and best of luck!

Cheers,
John

**Comment by jlpoolen** [comment]
https://www.crowdsupply.com/electronut-labs/mico
